os:
  - linux

dist: trusty

language: node_js
node_js: 8

cache:
  directories:
    - node_modules

install:
  - npm install yarn -g
  - yarn
  - yarn add codecov

jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: test
      script: yarn test && codecov
