os:
  - linux

dist: trusty

language: node_js
node_js: 8

cache:
  directories:
    - node_modules

before_install:
  - npm run lint

install:
  - npm install

jobs:
  include:
    - stage: test
      script: npm run test
