os:
  - linux

dist: trusty

language: node_js
node_js: 8
addons:
  chrome: stable

cache: npm

env:
  # Use light theme to avoid dark input fields in Firefox
  - GTK_THEME=Adwaita:light

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install libcairo2-dev libgif-dev libjpeg-dev libpango1.0-dev
install:
  - nvm install
  - nvm use
  - npm install

jobs:
  include:
    - stage: lint
      if: type != api
      script: npm run lint
    - stage: test
      if: type != api
      script: npm run test && codecov
    - stage: packtracker
      if: type != api
      script: npm run build
    - stage: lighthouse
      if: type = api
      script: npm run lh -- --perf=96 --bp=96 --no-comment $SITE_URL
    - stage: e2e
      if: type = api
      script: npm run install-selenium && xvfb-run --server-args="-screen 0 1200x800x24" npm run e2e || (errorshots push s3 && false)

notifications:
  webhooks:
    urls:
      - https://ooh7dsgcya.execute-api.us-east-1.amazonaws.com/dev/github-status
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
