os:
  - linux

dist: xenial

language: node_js
node_js: 10
addons:
  chrome: stable

cache: yarn

env:
  # Use light theme to avoid dark input fields in Firefox
  - GTK_THEME=Adwaita:light

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install libcairo2-dev libgif-dev libjpeg-dev libpango1.0-dev
install:
  - nvm install
  - nvm use
  - yarn --frozen-lockfile

jobs:
  include:
    - stage: lint
      if: type != api
      script: yarn lint
    - stage: test
      if: type != api
      script: yarn test:ci && codecov
    - stage: packtracker
      if: type != api
      script: yarn build
    - stage: lighthouse
      if: type = api
      script: yarn lh -- --perf=96 --bp=96 --no-comment $SITE_URL

notifications:
  webhooks:
    urls:
      - https://zm6ybeuoe8.execute-api.us-east-1.amazonaws.com/dev/github-status
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
