os:
  - linux

dist: trusty

language: node_js
node_js: 8
addons:
  chrome: stable

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

cache:
  directories:
    - node_modules

install:
  - npm install yarn -g
  # https://github.com/yarnpkg/yarn/issues/2738#issuecomment-342296820
  - yarn config set registry https://registry.npmjs.org
  - yarn

jobs:
  include:
    - stage: lint
      if: type != api
      script: yarn lint
    - stage: test
      if: type != api
      script: yarn test && codecov
    - stage: e2e
      if: type = api
      script: yarn install-selenium && yarn e2e

notifications:
  webhooks:
    urls:
      - https://ooh7dsgcya.execute-api.us-east-1.amazonaws.com/dev/github-status
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
