os:
  - linux

dist: trusty

language: node_js
node_js: 8
addons:
  chrome: stable

cache:
  directories:
    - node_modules

env:
  # Use light theme to avoid dark input fields in Firefox
  - GTK_THEME=Adwaita:light

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install libcairo2-dev libgif-dev libjpeg-dev libpango1.0-dev
install:
  - npm install

jobs:
  include:
    - stage: lint
      if: type != api
      script: npm runt lint
    - stage: test
      if: type != api
      script: npm runt test && codecov
    - stage: e2e
      if: type = api
      script: npm runt install-selenium && xvfb-run --server-args="-screen 0 1200x800x24" npm runt e2e || (errorshots push s3 && false)

notifications:
  webhooks:
    urls:
      - https://ooh7dsgcya.execute-api.us-east-1.amazonaws.com/dev/github-status
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
