export const FETCH_SHELTERS = 'FETCH_SHELTERS';
export const FETCH_SHELTERS_SUCCESS = 'FETCH_SHELTERS_SUCCESS';
export const FETCH_SHELTERS_FAILED = 'FETCH_SHELTERS_FAILED';

export const FETCH_SINGLE_SHELTER = 'FETCH_SINGLE_SHELTER';
export const FETCH_SINGLE_SHELTER_SUCCESS = 'FETCH_SINGLE_SHELTER_SUCCESS';
export const FETCH_SINGLE_SHELTER_FAILED = 'FETCH_SINGLE_SHELTER_FAILED';

export const FETCH_ROUTE_TO_SHELTER = 'FETCH_ROUTE_TO_SHELTER';
export const FETCH_ROUTE_TO_SHELTER_SUCCESS = 'FETCH_ROUTE_TO_SHELTER_SUCCESS';
export const FETCH_ROUTE_TO_SHELTER_FAILED = 'FETCH_ROUTE_TO_SHELTER_FAILED';

export const SELECT_SHELTER = 'SELECT_SHELTER';
export const UNSELECT_SHELTER = 'UNSELECT_SHELTER';

export const SELECT_ADDRESS = 'SELECT_ADDRESS';

export const CLEAR_ERROR = 'CLEAR_ERROR';

export const SET_BOUNDS = 'SET_BOUNDS';
