export const FETCH_SHELTERS = 'FETCH_SHELTERS';
export const FETCH_SHELTERS_SUCCESS = 'FETCH_SHELTERS_SUCCESS';
export const FETCH_SHELTERS_FAILED = 'FETCH_SHELTERS_FAILED';

export const FETCH_ROUTE_TO_SHELTER = 'FETCH_ROUTE_TO_SHELTER';
export const FETCH_ROUTE_TO_SHELTER_SUCCESS = 'FETCH_ROUTE_TO_SHELTER_SUCCESS';
export const FETCH_ROUTE_TO_SHELTER_FAILED = 'FETCH_ROUTE_TO_SHELTER_FAILED';

export const SELECT_SHELTER = 'SELECT_SHELTER';

export const CLEAR_ERROR = 'CLEAR_ERROR';
