export const GET_CURRENT_POSITION = 'GET_CURRENT_POSITION';
export const GET_CURRENT_POSITION_FAILED = 'GET_CURRENT_POSITION_FAILED';
export const GET_CURRENT_POSITION_SUCCESS = 'GET_CURRENT_POSITION_SUCCESS';

export const SELECT_ADDRESS = 'SELECT_ADDRESS';

