export const GET_CURRENT_POSITION = 'GET_CURRENT_POSITION';
export const GET_CURRENT_POSITION_FAILED = 'GET_CURRENT_POSITION_FAILED';
export const GET_CURRENT_POSITION_SUCCESS = 'GET_CURRENT_POSITION_SUCCESS';

export const RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const SELECT_ADDRESS = 'SELECT_ADDRESS';

