export const FETCH_ADDRESS_SUGGESTIONS = 'FETCH_ADDRESS_SUGGESTIONS';
export const FETCH_ADDRESS_SUGGESTIONS_SUCCESS = 'FETCH_ADDRESS_SUGGESTIONS_SUCCESS';
export const FETCH_ADDRESS_SUGGESTIONS_FAILED = 'FETCH_ADDRESS_SUGGESTIONS_FAILED';

export const SELECT_ADDRESS = 'SELECT_ADDRESS';

export const REVERSE_GEOCODE_POSITION = 'REVERSE_GEOCODE_POSITION';
export const REVERSE_GEOCODE_POSITION_SUCCESS = 'REVERSE_GEOCODE_POSITION_SUCCESS';
export const REVERSE_GEOCODE_POSITION_FAILED = 'REVERSE_GEOCODE_POSITION_FAILED';
